### ISSUE TITLE
Upstream dependency OGC API breaks validation

### ISSUE THREAD

**Issue by joachse** [OMSA-Open-Mobility-Sales-API/OMSA#1]
After bundling OMSA specification there is a validation error on a property coming from an upstream dependency named `transmissionMode`. Their default value is a array containing value, but it should only be a string.

```
    transmissionMode:
      type: string
      enum:
        - value
        - reference
      default:
        - value
```
should be:
```
    transmissionMode:
      type: string
      enum:
        - value
        - reference
      default: value
```

**Suggested solution**
Fix upstream dependency by submitting a issue or PR
