### ISSUE TITLE
AdditionalProperties causing compile errors

### ISSUE THREAD

**Issue by arnabkd** [OMSA-Open-Mobility-Sales-API/OMSA#4]
## Root cause
This is a [long-standing bug](https://github.com/OpenAPITools/openapi-generator/issues/4244) in the openapi-generator, which will probably not be adressed.

However, this still creates a problem for us when we are trying to generate code from the spec. 

```
    # Example type to demonstrate the problem
    myType:
      type: object
      additionalProperties: true
      properties:
        id:
          type: string
```

This generates the following
```
data class MyType(

    @get:JsonProperty("id") val id: kotlin.String? = null
    ) : kotlin.collections.HashMap<String, kotlin.Any>{

}

```

The issue is that the constructor for the HashMap is not being invoked, and I don't know a quick way to fix this without creating a PR to the openapi generator repo and getting it approved.

## Discussion

The main question we should think about, is:
Is it necessary to have these additional properties at this point? Is it possible to just omit that for now, and rather add fields in later if necessary?  

Are there other alternatives to just opening the type up to all kinds of arbitrary fields?
